problems = {
    'p0': "Consider points A, B, C, and D arranged to form trapezoid ABCD, where sides AD and BC are congruent. Place point E on the circle that has B as its center and a radius equal to BD. Prove that BD over DE is identical to DE over BD.",
    'p1': "In the right angle trapezoid ABCD, sides AB and AD are arranged to meet at a right angle. Prove that AB is perpendicular to AD.",
    'p2': "In a quadrilateral composed of vertices A, B, C, and D, the length of segment AD matches that of segment BC. A circle is centered at vertex A, and its radius is equal to the length of segment AD. On this circle lies point E. The segment FE is constructed to be equal in length to segment DC. Prove that A,D,E are not collinear.",
    'p3': "In the right-angled trapezoid ABCD, AB is orthogonal to AD. Consider point E placed on the bisector of ∠ACE, where line CD divides the angle into two equal parts. Within triangle DAB, I denotes the excenter, and F, G, H are its points of tangency. Introduce point J as the intersection of the external angle bisectors of triangle AIB. Define point K in such a way that lines KB and HD are parallel, and lines FK and AG are also parallel, with the intersection of lines KB and FK occurring at K. Prove that CD is parallel to HI.",
    'p4': "Points B, A, C, and D define the vertices of trapezoid ABCD. Complementarily, EFGHI forms a pentagonal configuration. Point J is defined through reflection across line EB, mirroring the position of point G. Point K is established where a perpendicular line from F intersect line AE. For triangle DHF, points M, N, L, and the nine-point center O are arranged such that circle O intersects line HF at point L, line FD at point M, and line DH at point N. Lastly, point P is positioned such that it lies on a line through J, forming a right angle with line KF. Prove that angle BJE is identical to ∠EGB.",
    'p5': "Points A, B, C, and D are arranged to form square ABCD. Additionally, point E is positioned on line segment AC, precisely at its midpoint. Prove that BD parallel to BD.",
    'p6': "In the isosceles triangle ABC, where the right angle is located at vertex A, point D is positioned so that angle CBD equals angle ABC. Prove that AB is parallel to AB.",
    'p7': "Consider three points B, A, and C forming triangle ABC with the length of side BC being twice that of AB. Define point D such that line segment DB is a tangent to a circle centered at C with a radius equal to CB, touching this circle at point D. Furthermore, consider points E, F, and G which together define an equilateral triangle EFG. Prove that E,F,G are not collinear.",
    'p8': "Let B, A, D, and C be points defining a right angle trapezoid ABCD where AB is perpendicular to AD. Point E is positioned on line segment DC. Prove that AD is perpendicular to CD."
}
